-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 08:54:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema denton
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema denton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `denton` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `denton` ;

-- -----------------------------------------------------
-- Table `denton`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`organization` (
  `organization_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`organization_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(128) NOT NULL COMMENT '',
  `organization_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`location_id`)  COMMENT '',
  INDEX `loc_org_fk_idx` (`organization_id` ASC)  COMMENT '',
  CONSTRAINT `loc_org_fk`
    FOREIGN KEY (`organization_id`)
    REFERENCES `denton`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(128) NULL COMMENT '',
  `password` VARCHAR(32) NOT NULL COMMENT '',
  `location_id` INT NOT NULL COMMENT '',
  `user_alias` VARCHAR(64) NULL COMMENT '',
  `msisdn` VARCHAR(32) NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `user_loc_fk_idx` (`location_id` ASC)  COMMENT '',
  UNIQUE INDEX `user_alias_UNIQUE` (`user_alias` ASC)  COMMENT '',
  UNIQUE INDEX `msisdn_UNIQUE` (`msisdn` ASC)  COMMENT '',
  CONSTRAINT `user_loc_fk`
    FOREIGN KEY (`location_id`)
    REFERENCES `denton`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`chronology_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`chronology_type` (
  `chronology_type_code` VARCHAR(20) NOT NULL COMMENT '',
  `display_name_de` VARCHAR(50) NOT NULL COMMENT '',
  `display_name_en` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`chronology_type_code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`text_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`text_pool` (
  `text_pool_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `browser_language_code` VARCHAR(10) NULL COMMENT '',
  `text` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`text_pool_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`chronology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`chronology` (
  `chronology_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `chronology_type_code` VARCHAR(20) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `time_created` TIMESTAMP NOT NULL COMMENT '',
  `text_pool_id` INT NULL COMMENT '',
  PRIMARY KEY (`chronology_id`)  COMMENT '',
  INDEX `chron_type_fk_idx` (`chronology_type_code` ASC)  COMMENT '',
  INDEX `user_fk_idx` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `type_usr_time_uk` (`chronology_type_code` ASC, `user_id` ASC, `time_created` ASC)  COMMENT '',
  INDEX `text_pool_fk_idx` (`text_pool_id` ASC)  COMMENT '',
  CONSTRAINT `chron_type_fk`
    FOREIGN KEY (`chronology_type_code`)
    REFERENCES `denton`.`chronology_type` (`chronology_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `denton`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `text_pool_fk`
    FOREIGN KEY (`text_pool_id`)
    REFERENCES `denton`.`text_pool` (`text_pool_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `denton`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `denton`.`country` (
  `country_code` VARCHAR(3) NOT NULL COMMENT '',
  `phone_prefix` SMALLINT(6) NOT NULL COMMENT '',
  `name_de` VARCHAR(45) NOT NULL COMMENT '',
  `name_en` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`country_code`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
